Controllers/AttributesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProspectManagementTool.Data;
using ProspectManagementTool.Models;

namespace ProspectManagementTool.Controllers
{
    public class AttributesController : Controller
    {
        private readonly ProspectManagementContext _context;

        public AttributesController(ProspectManagementContext context)
        {
            _context = context;
        }

        // GET: Attributes
        public async Task<IActionResult> Index()
        {
            var attributes = from a in _context.Attributes.OrderBy(a => a.AttributeName)
                        select a;
            return View(await attributes.ToListAsync());
        }

        // GET: Attributes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attribute = await _context.Attributes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (attribute == null)
            {
                return NotFound();
            }

            return View(attribute);
        }

        // GET: Attributes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Attributes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,AttributeName")] Models.Attribute attribute)
        {
            if (ModelState.IsValid)
            {
                _context.Add(attribute);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(attribute);
        }

        // GET: Attributes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attribute = await _context.Attributes.FindAsync(id);
            if (attribute == null)
            {
                return NotFound();
            }
            return View(attribute);
        }

        // POST: Attributes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,AttributeName")] Models.Attribute attribute)
        {
            if (id != attribute.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(attribute);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttributeExists(attribute.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(attribute);
        }

        // GET: Attributes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attribute = await _context.Attributes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (attribute == null)
            {
                return NotFound();
            }

            return View(attribute);
        }

        // POST: Attributes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var attribute = await _context.Attributes.FindAsync(id);
            try
            {
                _context.Attributes.Remove(attribute);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException dex)
            {
                if (dex.InnerException.Message.Contains("FK_Prospects_Attribute_AttributeID"))
                {
                    ModelState.AddModelError("", "Cannot delete an attribute that is assigned to players.");
                }
                else
                {
                    ModelState.AddModelError("", "Delete failed. Please try again.");
                }
            }
            return View(attribute);
        }

                private bool AttributeExists(int id)
        {
            return _context.Attributes.Any(e => e.ID == id);
        }
    }
}

Controllers/DraftsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProspectManagementTool.Data;
using ProspectManagementTool.Models;

namespace ProspectManagementTool.Controllers
{
    public class DraftsController : Controller
    {
        private readonly ProspectManagementContext _context;

        public DraftsController(ProspectManagementContext context)
        {
            _context = context;
        }

        // GET: Drafts
        public async Task<IActionResult> Index()
        {
            ViewData["TeamID"] = new SelectList(_context.Teams.OrderBy(a => a.HockeyTeam), "ID", "HockeyTeam");
            PopulateDropDownLists();

            var draft = from d in _context.Drafts
                        .Include(d => d.Team).ThenInclude(d => d.Prospects).Include(d => d.Attribute)
                        select d;
            return View(await draft.ToListAsync());
        }

        // GET: Drafts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var draft = await _context.Drafts.Include(d => d.Team).ThenInclude(d => d.Prospects).Include(d => d.Attribute)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (draft == null)
            {
                return NotFound();
            }

            return View(draft);
        }

        // GET: Drafts/Create
        public IActionResult Create()
        {
            PopulateDropDownLists();
            return View();
        }

        // POST: Drafts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,DraftName,DraftPosition,DraftOV,DraftPotential,DraftAge,AttributeID,DraftInitialRating,TeamID")] Draft draft)
        {
            if (ModelState.IsValid)
            {
                _context.Add(draft);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AttributeID"] = new SelectList(_context.Attributes, "ID", "AttributeName", draft.AttributeID);
            return View(draft);
        }

        // GET: Drafts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var draft = await _context.Drafts
                .Include(d => d.Attribute).Include(d => d.Team).ThenInclude(d =>d.Prospects)
                .AsNoTracking()
                .SingleOrDefaultAsync(d => d.ID == id);

            if (draft == null)
            {
                return NotFound();
            }
            PopulateDropDownLists(draft);
            return View(draft);
        }

        // POST: Drafts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,DraftName,DraftPosition,DraftOV,DraftPotential,DraftAge,AttributeID,DraftInitialRating,TeamID")] Draft draft)
        {
            var draftToUpdate = await _context.Drafts
       .Include(p => p.Team).Include(p => p.Attribute)
       .SingleOrDefaultAsync(p => p.ID == id);

            if (draftToUpdate == null)
            {
                return NotFound();
            }

            if (await TryUpdateModelAsync<Draft>(draftToUpdate, "", d => d.DraftName, d => d.DraftPosition, d => d.DraftOV, d => d.DraftPotential,
                d => d.DraftAge, d => d.DraftInitialRating, d => d.AttributeID, d => d.TeamID))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    throw;
                }
            }
            PopulateDropDownLists(draftToUpdate);
            return View(draftToUpdate);
        }

        // GET: Drafts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var draft = await _context.Drafts
                .FirstOrDefaultAsync(m => m.ID == id);
            if (draft == null)
            {
                return NotFound();
            }

            return View(draft);
        }

        // POST: Drafts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var draft = await _context.Drafts.FindAsync(id);
            _context.Drafts.Remove(draft);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DraftExists(int id)
        {
            return _context.Drafts.Any(e => e.ID == id);
        }

        private SelectList AttributeSelectList(int? selectedId)
        {
            return new SelectList(_context.Attributes.OrderBy(d => d.AttributeName), "ID", "AttributeName", selectedId);
        }
        private SelectList TeamSelectList(int? selectedId)
        {
            return new SelectList(_context.Teams
                .OrderBy(d => d.HockeyTeam), "ID", "HockeyTeam", selectedId);
        }
        private void PopulateDropDownLists(Draft draft = null)
        {
            ViewData["TeamID"] = TeamSelectList(draft?.TeamID);
            ViewData["AttributeID"] = AttributeSelectList(draft?.AttributeID);
        }
    }
}

Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProspectManagementTool.Data;
using ProspectManagementTool.Models;

namespace ProspectManagementTool.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ProspectManagementContext _context;

        public TeamsController(ProspectManagementContext context)
        {
            _context = context;
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            var teams = from t in _context.Teams.OrderBy(t => t.HockeyTeam)
                        select t;
            return View(await teams.ToListAsync());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .FirstOrDefaultAsync(m => m.ID == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CityName,TeamName")] Team team)
        {
            if (ModelState.IsValid)
            {
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CityName,TeamName")] Team team)
        {
            if (id != team.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .FirstOrDefaultAsync(m => m.ID == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            try
            {
                _context.Teams.Remove(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException dex)
            {
                if (dex.InnerException.Message.Contains("FK_Prospects_Teams_TeamID"))
                {
                    ModelState.AddModelError("", "Cannot delete a team with prospects assigned to it");
                }
                else
                {
                    ModelState.AddModelError("", "Delete failed. Please try again.");
                }
            }
            return View(team);
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Prospect Manager - @ViewData["Title"]</title>
    <link runat="server" rel="shortcut icon" href="PensFavicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="~/PensFavicon.ico" type="image/ico" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prospect Management Tool</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial"/>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prospects" asp-action="Index">Prospects</a>
                        </li>
                        <li>
                            <link class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Drafts" asp-action="Index">Draft List</a>
                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <link class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Teams</a>
                            </li>
                            <li>
                                <link class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attributes" asp-action="Index">Attributes</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ProspectManagementTool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>